// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLsIwC5BHwIYLjpZX4GIAQQv8IOFw95Uw',
    appId: '1:28407943478:web:a08495ec3e960e7025a397',
    messagingSenderId: '28407943478',
    projectId: 'project-switch-7445c',
    authDomain: 'project-switch-7445c.firebaseapp.com',
    storageBucket: 'project-switch-7445c.appspot.com',
    measurementId: 'G-ZZ3B42B14J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALZ8q2e85zZvT2MOA4_hAk5iuj6Pg5EOU',
    appId: '1:28407943478:android:383f135947a816aa25a397',
    messagingSenderId: '28407943478',
    projectId: 'project-switch-7445c',
    storageBucket: 'project-switch-7445c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC58qe6AZ6DOejeJKBOTvv5s5KsTsX1Gp4',
    appId: '1:28407943478:ios:94ae35648f3c328925a397',
    messagingSenderId: '28407943478',
    projectId: 'project-switch-7445c',
    storageBucket: 'project-switch-7445c.appspot.com',
    iosClientId: '28407943478-4jd41075q6bi5i3e6iudbnmueiius4r8.apps.googleusercontent.com',
    iosBundleId: 'me.bhavuk.swtich.projectSwitch',
  );
}
